### ISSUE TITLE
Speedrun.com Profile Redirect

### ISSUE THREAD

**Issue by Tobik81** [jannik323/KarlsonScore#15]
Redirect the user to a player's speedrun.com profile page upon clicking their name and/or clicking their total score.

Clicking the level score could additionally redirect to "level runs" page on the profile, while clicking the full-game score could redirect to the player's run.

**Comment by jannik323** [comment]
@Tobik81 The Player Name now links to a players profile on sr.c .
Is that what you had in mind?
Linking to a certain run will need some weird extra work and linking to the level section seems useless since its just 1 click from the profile page which is already getting linked.

**Comment by Tobik81** [comment]
Yeah, that's exactly what I had in mind.
Linking to the levels page does seem redundant, and linking to a run isn't really necessary as well, since it's also just a click away from the profile page. I feel like that's enough.
